version: '3.8'

networks:
  my-bridged-network:
    driver: bridge

services:
  my-postgres-db:  # Custom name for the database container
    container_name: my-postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432" # Default Postgres port
    networks:
      - my-bridged-network

  app:
    container_name: my-app
    build: .
    ports:
      - "8080:8080" # Default Spring Boot port
    networks:
      - my-bridged-network
    depends_on:
      - my-postgres-db  # Use the custom service name here

  prometheus:
    container_name: my-prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro  # Mount your configuration file
    ports:
      - "9090:9090"
    networks:
      - my-bridged-network
    depends_on:
      - app

  garfana:
    container_name: my-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - my-bridged-network
    depends_on:
      - prometheus
